\clearpage

# Introduction

Advances in predictive analytics and diagnostic technologies are crucial for
improving public health. Early detection and accurate diagnosis of diseases 
like cancer significantly improve treatment outcomes and survival rates. Since 
breast cancer is one of the most common cancers affecting women worldwide, 
developing reliable prediction methods is essential. This study aims to
explore advanced data analysis techniques to improve the accuracy of breast
cancer diagnosis.

Predicting breast cancer involves analyzing various physiological and
pathological features that indicate malignant tumors. Traditional methods 
often rely on clinical exams and imaging techniques, which, while 
effective, can be enhanced by computational methods.

Principal Component Analysis (PCA) is a useful tool for reducing the number of 
variables in a dataset. By simplifying the data without losing important 
information, PCA improves the performance of predictive models. In this study,
we use PCA on the Breast Cancer Wisconsin (Diagnostic) dataset to streamline
the features and improve the prediction model's efficiency. This step is 
essential for handling high-dimensional data in medical diagnostics and ensures 
that the model is robust and easy to interpret.

Logistic Regression, a common method for binary classification, is used to 
predict whether a tumor is malignant or benign. This technique is well-suited 
for medical diagnostics because it provides probabilities and can handle 
various predictor variables. By applying Logistic Regression to the 
PCA-transformed dataset, we aim to achieve high accuracy in predicting breast
cancer. Combining PCA and Logistic Regression offers a comprehensive approach 
to addressing the complexity of breast cancer prediction.

The dataset used in this study is the Breast Cancer Wisconsin (Diagnostic) 
dataset, a well-known resource in medical research. This dataset includes 
various features extracted from digitized images of fine needle aspirate (FNA) 
of breast masses[@UCI95:bc], making it ideal for predictive analysis. We conducted the 
analysis and reporting using _R Studio (version 4.3.2, released on 
October 31, 2023)_, which provides a robust environment for statistical 
computing and graphics. Through this study, we aim to enhance breast cancer 
detection and improve patient outcomes, supporting the broader goal of 
advancing healthcare through data-driven methods.
