
```{r, echo = FALSE, include = FALSE}
if (!requireNamespace("knitr", quietly = TRUE)) {
  install.packages("knitr", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("kableExtra", quietly = TRUE)) {
  install.packages("kableExtra", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("tidyverse", quietly = TRUE)) {
  install.packages("tidyverse", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("cowplot", quietly = TRUE)) {
  install.packages("cowplot", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("gridExtra", quietly = TRUE)) {
  install.packages("gridExtra", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("corrplot", quietly = TRUE)) {
  install.packages("corrplot", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("factoextra", quietly = TRUE)) {
  install.packages("factoextra", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("stargazer", quietly = TRUE)) {
  install.packages("stargazer", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("lmtest", quietly = TRUE)) {
  install.packages("lmtest", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("caret", quietly = TRUE)) {
  install.packages("caret", repos ="http://cran.us.r-project.org")
}

if (!requireNamespace("pROC", quietly = TRUE)) {
  install.packages("pROC", repos ="http://cran.us.r-project.org")
}


library(knitr)
library(kableExtra)

library(psych)

library(tidyverse)
library(dplyr)

library(ggplot2)
library(gridExtra)
library(cowplot)

library(corrplot)
library(factoextra)

library(stargazer)
library(lmtest)
library(caret)
library(pROC)
```

```{r setup, include=FALSE} 
opts_chunk$set(warning = FALSE, message = FALSE) 
```

